### ISSUE TITLE
原图地址不对

### ISSUE THREAD

**Issue by taofei** [jwenjian/usda-fruit-img-spider#1]
__parse_ori_img_url方法里
return 'https://usdawatercolors.nal.usda.gov/download/{}/screen'.format(img_id)
这里返回的仍然是缩略图，大小只有100+kb

原图地址格式应该为：
return 'https://usdawatercolors.nal.usda.gov/pom/download.xhtml?id={}'.format(img_id)
大小在7.5mb上下

**Comment by jwenjian** [comment]
确实
